const fs = require('fs');
const path = require('path');

module.exports = {
    addSomethingPage: (req, res) => {
        res.sendFile(path.join(__dirname+'/addSomething.html'));
    },
    addSomething: (req, res) => {
        
        let id = 0 ; 
        let owner = "testAutoGeneratedOwner" ; 
        let nametoinsert = req.body.nameOfSomething;
        let description = "testAutoGeneratedDescription";
        let date = "2001-01-01" ;
        
        let query = "INSERT INTO `testtmp` (id, owner, name, description, date) VALUES ('" +
        id + "', '" + owner + "', '" + nametoinsert + "', '" + description + "', '" + date + "')";
        db.query(query, (err, result) => {
            if (err) {
                return res.status(500).send(err); 
            }
            res.redirect('/');
        });
    }
};